<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\SMMPI.Application\SMMPI.Application.csproj" />
    <ProjectReference Include="..\..\Core\SMMPI.Domain\SMMPI.Domain.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="OAuth2Bridge" Version="1.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
	</ItemGroup>

</Project>
